name: littoral_pipeline
channels:
  - conda-forge
  - menpo
  - meepio
dependencies:
  - python==3.10.12
  - pandas
  - numpy==1.26.0
  - pillow
  - scikit-image
  - geemap
  - earthengine-api
  - requests
  - ipykernel
  - opencv-python==4.10.0.84
  - pytorch
  - torchvision
  - tqdm
  - pip
  - pip:
    - huggingface-hub==0.25.2